version: '3'

services:
  db:
    image: mysql:8
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    container_name: ecommerce-db
    volumes:
      - ./mysql:/var/lib/mysql